// FLORIDA DAN — the collectible Rap Sheet. Every headline the game can print, how to
// recognize it, and a vague hint for the ones you haven't earned yet. Found headlines
// persist across playthroughs (localStorage), so the hunt continues after court.
'use strict';
const HEADLINES = [
  // ---- Florida Man opportunities (side gigs) ----
  ['gigBeer', /BAR THAT IS ALSO BASICALLY A BOAT/, 'Skeeter’s bar is thirsty.'],
  ['gigPool', /ALLIGATOR FROM KIDDIE POOL/, 'Palmetto Pines has a pool problem.'],
  ['gigMattress', /MOTEL MATTRESS/, 'Room 4 left something behind.'],
  ['gigFireworks', /PRODUCT TESTS/, 'Boomer needs a tester with no eyebrows.'],
  ['gigTrial', /LAKE SPEED RECORD/, 'Bubba’s lake record can be beaten.'],
  ['gigCow', /HERDS ESCAPED COW/, 'Earl’s cow keeps getting out.'],
  ['airboat', /BUYS AIRBOAT/, 'Bubba sells something with a very big fan.'],
  ['recliner', /RECLINER ON PORCH/, 'Every office needs a chair.'],
  ['gigCafecito', /CAFECITO TO SOUTH BEACH LIFEGUARDS/, 'Abuela worries about the lifeguards.'],
  ['gigRematch', /BEATS ROLLERBLADER TWICE/, 'Raul wants a rematch.'],
  ['gigPickles', /IGUANA IN BOW TIE/, 'Sheila lost a very dapper lizard.'],
  ['ring', /FINDS WEDDING RING WITH METAL DETECTOR/, 'The beach hides things. Bring the right tool.'],
  ['doubloon', /FINDS PIRATE GOLD/, 'Somewhere under the sand, there’s real treasure.'],
  // ---- Daytona ----
  ['daytona', /ARRIVES IN DAYTONA/, 'Take the Greyhound north, after Miami.'],
  ['donutRun', /THROUGH DONUT DRIVE-THRU/, 'The pace car goes where the pace car wants.'],
  ['pitStop', /FOUR TIRES IN RECORD TIME/, 'Rusty’s pit crew quit. Somebody’s gotta change tires.'],
  ['armWrestle', /BIKER NAMED "TINY"/, 'Tiny has something that isn’t his.'],
  ['pacing', /RECKLESS PACING/, 'Volusia County wants a word.'],
  ['qualify', /QUALIFIES FOR DAYTONA 250/, 'One fast lap in the #29.'],
  ['daytona250', /WINS DAYTONA 250/, 'Win the big one.'],
  ['chipBusted', /ENERGY DRINK MOGUL ARRESTED/, 'Somebody sabotaged the #29.'],
  ['gigDonuts', /DONUTS TO NASCAR PIT CREWS/, 'Donna’s donuts need a delivery man.'],
  ['gigHelmet', /LUCKY HELMET/, 'Tiny lost something on the beach.'],
  ['gigPit', /PIT DRILL RECORD/, 'Tammy Jo runs pit drills.'],
  // ---- the Keys ----
  ['keys', /ARRIVES IN THE KEYS/, 'Take the Greyhound all the way south, after Daytona.'],
  ['bridge', /SEVEN MILE BRIDGE/, 'Seven miles. One cooler. Floor it.'],
  ['republic', /SOVEREIGN NATION/, 'A houseboat, a sunset, eleven beers.'],
  ['citizenCat', /MR\. TOES/, 'Miss Pearl’s cat likes fish.'],
  ['citizenRooster', /ROOSTER GRANTED CITIZENSHIP/, 'The Republic needs citizens. Birds count.'],
  ['bro', /RENOUNCES U\.S\. CITIZENSHIP/, 'Brayden (bro) wants a chug-off.'],
  ['recognized', /FORMALLY "RECOGNIZES"/, 'Dance for the Mallory Square sunset crowd.'],
  ['sister', /SISTER NATION/, 'Win Case Eight.'],
  ['snorkel', /GOES SNORKELING IN JORTS/, 'Go under. Anywhere.'],
  ['lobster', /LOBSTER WITH BARE HANDS/, 'Spiny lobsters hide on the reef.'],
  ['goldCoin', /300-YEAR-OLD GOLD COIN/, 'Snorkel under the old bridge.'],
  ['tarpon', /FEEDS TARPON BY HAND/, 'Old Gus’s tarpon are hungry.'],
  ['rexChase', /RECOVERS 300-YEAR-OLD CHEST/, 'Somebody grabs the chest. Chase him.'],
  ['galleon', /GRAND THEFT GALLEON/, 'Win Case Nine.'],
  ['keyDeer', /KEY DEER/, 'Don’t. Just don’t.'],
  ['buoy', /PHOTO WITH BUOY/, 'Everybody takes the same photo.'],
  ['gigRoosters', /EVICTS THREE ROOSTERS/, 'Moe has a rooster problem.'],
  ['gigLobsters', /HAND-CAUGHT LOBSTERS TO CONCH SHACK/, 'Joelle needs lobsters.'],
  ['gigKayak', /HALFWAY TO CUBA/, 'Somebody paddled for Cuba in Tom’s kayak.'],

  // ---- the Flamingo case ----
  ['fry', /DEEP-FRIES FROZEN TURKEY/, 'Merle, a frozen turkey, and hot oil.'],
  ['roof', /FALLS OFF ROOF/, 'Something that doesn’t belong is on your roof.'],
  ['raccoonFace', /ICE MACHINE USING HIS FACE/, 'Darlene’s ice machine has a tenant.'],
  ['manatee', /RIDING MANATEE/, 'A sea cow of truth appears during the storm.'],
  ['acquitted', /ACQUITTED OF BEING A FLORIDA MAN/, 'Friday. Court. A familiar visor.'],
  // ---- the Manatee Matter ----
  ['kaydenContent', /THREE FLORIDA MAN THINGS TO GET ONE/, 'Pay a teenager in content.'],
  ['lagoon', /CLEANS UP LAGOON/, 'Dr. Pam wants the lagoon clean.'],
  ['lettuceBuy', /BUYS LETTUCE/, 'Buy a vegetable. Shock a clerk.'],
  ['mannyMidnight', /FEEDING LETTUCE TO MANATEE/, 'Midnight snack for a sea cow.'],
  ['mannyCourt', /MANATEE TESTIFIES IN COURT/, 'Win Case Two.'],
  ['objectAll', /OBJECTS AT EVERY LIE/, 'Object at every lie. Only the lies.'],
  ['cleanCase', /BARELY ANY HEADLINES/, 'Get through a whole case without making the paper. Much.'],
  // ---- the Skunk Ape Affair ----
  ['trailcam', /TRAIL CAM CAPTURES/, 'There’s a camera in the Glades.'],
  ['apeBeer', /SHARES BEER WITH SKUNK APE/, 'Offer the big guy a cold one.'],
  ['apePunch', /PUNCHES SKUNK APE/, 'Offer the big guy a knuckle sandwich.'],
  ['reunion', /REUNITE AFTER 30 YEARS/, 'Two old friends, one swamp.'],
  ['apeCourt', /SKUNK APE APPEARS IN COURT/, 'Win Case Three.'],
  ['fmoty', /FLORIDA MAN OF THE YEAR/, 'The highest honor in the state.'],
  // ---- favors ----
  ['heist', /ROLLER DOG MACHINE FROM RACCOON CARTEL/, 'Darlene’s machine went missing.'],
  ['tour', /BETTER THAN DISNEY/, 'Show a visitor the real Florida.'],
  ['kevinWin', /DUMPSTER A RUG/, 'Kevin has a lottery feeling.'],
  ['tenFavors', /TEN FAVORS/, 'Be a good neighbor. Ten times.'],
  // ---- Miami ----
  ['miamiArrive', /ARRIVES IN MIAMI WITH A COOLER/, 'Take the Greyhound south.'],
  ['lamboSink', /PINK LAMBORGHINI DIRECTLY INTO ATLANTIC/, 'The valet needs a favor. The car doesn’t surf.'],
  ['lamboFish', /FISHES PINK LAMBORGHINI/, 'Something pink is at the bottom of the Atlantic.'],
  ['danceOff', /WINS DANCE-OFF AT CLUB SINUS/, 'Wedding moves, club floor.'],
  ['abuelaStory', /45-MINUTE STORY AT CAFÉ WINDOW/, 'Sit. Sip. Listen. The whole thing.'],
  ['raulRace', /BEATS ROLLERBLADER IN OCEAN DRIVE RACE/, 'Raul has never lost. Cafecito helps.'],
  ['canadian', /GIT" AT CANADIAN/, 'Somebody’s on Sheila’s chair.'],
  ['lamboCourt', /CLEARED IN PINK LAMBO CASE/, 'Win Case Four.'],
  ['baleFlyer', /POSTS FLYER: "FOUND: YOUR STUFF/, 'Return lost property. Be a good citizen.'],
  ['pastelSuit', /BUYS PASTEL SUIT/, 'Miami formal.'],
  ['yachtToss', /THROWN OFF YACHT PARTY/, 'Say something VERY Florida at a yacht party.'],
  ['pelicanBoss', /BOSS IS A PELICAN/, 'That pelican has been up to something.'],
  ['sinusCourt', /SINUS CARTEL RUN BY A PELICAN/, 'Win Case Five.'],
  ['grouper', /FISHES "SQUARE GROUPER"/, 'The ocean has bales in it.'],
  ['tarpon', /90-POUND TARPON/, 'The Silver King swims off the pier.'],
  // ---- gators ----
  ['wrestleGator', /WRESTLES ALLIGATOR "FOR FUN"/, 'Get hands-on with a gator.'],
  ['wrestleChuck', /ALLIGATOR NAMED "CHUCK," CALLS IT/, 'Chuck needs a hug. A firm one.'],
  ['punchGator', /PUNCHES ALLIGATOR IN THE FACE/, 'Gators respect one thing.'],
  ['punchChuck', /PUNCHES GATOR NAMED CHUCK/, 'Chuck needs a knuckle sandwich.'],
  ['bitten3', /BITTEN BY GATORS THREE TIMES/, 'Let the gators win. Thrice.'],
  // ---- substances ----
  ['sixBeers', /SIX BEERS/, 'Hydrate. A lot.'],
  ['sinus', /POWDER IS "SINUS MEDICINE/, 'It’s for your sinuses.'],
  ['ascend', /ASCENDS/, 'Sinus medicine + something from a cow pie.'],
  ['munchies', /EXTREMELY HIGH/, 'The munchies want a roller dog.'],
  ['incident', /HAS "INCIDENT"/, 'Never trust a roller dog. Never trust a toilet to be close.'],
  ['bo_roof', /GAS STATION ROOF/, 'Drink until everything goes black. (1/5)'],
  ['bo_cow', /SPOONING COW/, 'Drink until everything goes black. (2/5)'],
  ['bo_cone', /TRAFFIC CONE/, 'Drink until everything goes black. (3/5)'],
  ['bo_road', /NAPPING IN MIDDLE OF COUNTY ROAD/, 'Drink until everything goes black. (4/5)'],
  ['bo_potty', /NIGHT IN PORTA-POTTY/, 'Drink until everything goes black. (5/5)'],
  ['drunkFish', /CATCHES FISH WHILE DRUNK/, 'Fishing is easier with a buzz. Right?'],
  ['oregano', /BUYS "OREGANO" FROM MAN IN VAN/, 'There’s a van behind the Gulp-N-Go. It smells like a van.'],
  ['sharpieCoat', /MAN IN SHARPIE LAB COAT/, 'Miami has a “doctor” on the beach.'],
  // ---- the law ----
  ['coolerDUI', /DUI ON MOTORIZED COOLER/, 'The cooler has headlights for a reason.'],
  ['canCop', /HITS DEPUTY WITH BEER CAN/, 'Greet Rhonda the family way.'],
  ['caught', /LOW-SPEED CHASE|YOU CAN’T ARREST ME/, 'Get three stars of heat, then get caught.'],
  ['escHide', /HIDES FROM POLICE IN PORTA-POTTY/, 'Lose Rhonda somewhere that smells.'],
  ['escBoat', /ESCAPES POLICE IN JON BOAT/, 'Her cruiser can’t swim.'],
  ['escCooler', /EVADES DEPUTY ON MOTORIZED COOLER/, 'Outrun the law on something with headlights.'],
  ['escRun', /OUTRUNS DEPUTY IN FLIP-FLOPS/, 'Lose Rhonda on foot. Somehow.'],
  // ---- wildlife ----
  ['pythonHands', /PYTHON WITH BARE HANDS/, 'The Glades have noodles.'],
  ['pythonBounty', /FEET OF PYTHON, SAYS/, 'Rhonda pays by the foot. Bring a lot.'],
  ['punchPython', /PUNCHES PYTHON/, 'Stun a noodle the hard way.'],
  ['iguana', /FROZEN IGUANA/, 'It’s cold. Stand under a palm.'],
  ['punchCow', /PUNCHES COW/, 'The pasture has an innocent victim.'],
  ['punchPelican', /PUNCHES PELICAN/, 'Wipe the smug off a bird.'],
  ['pelicanTheft', /PELICAN STEALS/, 'Walk the dock with a fish in your bag.'],
  ['raccoonTheft', /RACCOON ROBS/, 'Trash pandas know where your pockets are.'],
  ['pelicanScream', /SCREAMS AT PELICAN/, 'Run completely out of chill.'],
  // ---- tourists ----
  ['gitTourist', /YELLS "GIT" AT TOURIST/, 'Not all visitors are welcome. Tell them.'],
  ['canTourist', /THROWS EMPTY AT TOURIST/, 'Welcome a visitor with a projectile.'],
  ['punchTourist', /PUNCHES TOURIST/, 'Give a visitor the REAL Florida experience.'],
  // ---- fishing & luck ----
  ['ronnie', /BIG RONNIE/, 'A legend lurks in deep water near Merle’s.'],
  ['cart', /SHOPPING CART VIA SWAMP/, 'Something with wheels is on the bottom.'],
  ['phone', /IPHONE OUT OF SWAMP/, 'Somebody’s mom keeps calling from the bottom of the swamp.'],
  ['scratch100', /WINS \$100/, 'Feeling lucky? Keep scratching.'],
  ['fireworks', /SETS OFF FIREWORKS/, 'Freedom Rockets aren’t just for the 4th.'],
];
const SHEET_KEY = 'floridaDan.sheet';
const Sheet = {
  found: (() => { try { return JSON.parse(localStorage.getItem(SHEET_KEY)) || {}; } catch (e) { return {}; } })(),
  total: () => HEADLINES.length,
  count() { return HEADLINES.filter(([k]) => this.found[k]).length; },
  keyFor(text) { const h = HEADLINES.find(([, re]) => re.test(text.toUpperCase())); return h ? h[0] : null; },
  // returns true the first time this headline is ever earned
  mark(text) {
    const k = this.keyFor(text); if (!k || this.found[k]) return false;
    this.found[k] = { day: Game.day, text };
    try { localStorage.setItem(SHEET_KEY, JSON.stringify(this.found)); } catch (e) { }
    return true;
  },
};
